# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonar-aws'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectVersion=1.0.0.0
            sonar.projectName=springsonarqube
            sonar.sources=src/main/java/
            sonar.language=java
            sonar.sourceEncoding=UTF-8
            sonar.jacoco.reportPaths=/home/vsts/work/1/s/**/jacoco.xml

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    allowBrokenSymlinks: false
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageFailIfEmpty: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: true
    effectivePomSkip: true
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'


- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
