# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonar-aws'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectVersion=1.0.0.0
            sonar.projectName=springsonarqube
            sonar.sources=src/main/java/
            sonar.language=java
            sonar.sourceEncoding=UTF-8
            sonar.jacoco.reportPaths=/home/vsts/work/1/s/**/jacoco.xml




- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'sonar:sonar'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false